const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function renderSignals(){ $('#signalRail').innerHTML=SIGNALS.map((s,i)=>`<article class="signal"><span>${String(i+1).padStart(2,'0')}</span><strong>${s[0]}</strong><h3>${s[1]}</h3><p>${s[2]}</p><small class="layer press">Source guide: ${s[3]}</small></article>`).join('') }
function renderStories(){const q=$('#storySearch').value.trim().toLowerCase(),t=$('#storyTheme').value;const rows=STORIES.filter(s=>(t==='all'||s.theme===t)&&Object.values(s).join(' ').toLowerCase().includes(q));$('#storyCount').textContent=`${rows.length} local ${rows.length===1?'story':'stories'} shown`;$('#storyGrid').innerHTML=rows.map(s=>`<article class="story"><div class="story-top"><span>${s.theme}</span><small>Page ${s.page}</small></div><h3>${s.title}</h3><p class="place">${s.place}</p><div class="story-flow"><p><b>Challenge</b>${s.problem}</p><p class="layer colleague press"><b>Local action</b>${s.action}</p><p><b>Result</b>${s.result}</p></div></article>`).join('')||'<p>No matching stories. Clear the filters to view the full atlas.</p>'}
function renderThemes(){const tabs=$('#themeTabs');tabs.innerHTML=THEMES.map((t,i)=>`<button role="tab" id="tab-${i}" aria-controls="panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-i="${i}">${String(i+1).padStart(2,'0')} ${t.name}</button>`).join('');function show(i){const t=THEMES[i];$$('[role=tab]').forEach((b,n)=>{b.setAttribute('aria-selected',n===i);b.tabIndex=n===i?0:-1});$('#themePanel').innerHTML=`<p class="kicker">Theme ${String(i+1).padStart(2,'0')}</p><strong class="theme-stat">${t.stat}</strong><h3>${t.line}</h3><p>${t.context}</p><div class="layer colleague press"><h4>What regions and cities ask for</h4><ul>${t.asks.map(a=>`<li>${a}</li>`).join('')}</ul></div>`}tabs.addEventListener('click',e=>{const b=e.target.closest('button');if(b)show(+b.dataset.i)});tabs.addEventListener('keydown',e=>{const current=+document.activeElement.dataset.i;if(!['ArrowDown','ArrowUp','ArrowRight','ArrowLeft'].includes(e.key))return;e.preventDefault();const d=['ArrowDown','ArrowRight'].includes(e.key)?1:-1,n=(current+d+THEMES.length)%THEMES.length;tabs.children[n].focus();show(n)});show(0)}
function renderDossiers(){const grouped={};STORIES.forEach(s=>(grouped[s.theme]??=[]).push(s));$('#dossiers').innerHTML=THEMES.map((t,i)=>`<details><summary><span>${String(i+1).padStart(2,'0')}</span>${t.name}<b>${t.stat}</b></summary><div class="dossier"><p>${t.context}</p><h4>Reusable framing</h4><p>${t.stat} ${t.line}. Attribute the figure to the European Committee of the Regions’ 2026 report and retain its stated period and scope.</p><h4>Relevant local examples</h4><ul>${STORIES.filter(s=>t.name.toLowerCase().includes(s.theme.toLowerCase().split(' ')[0])||s.theme==='Climate'&&i===4||s.theme==='Preparedness'&&i===3||s.theme==='Democracy'&&i===7||s.theme==='Finance'&&i===8||s.theme==='Demography'&&i===9).slice(0,3).map(s=>`<li>${s.place}: ${s.result} (p. ${s.page})</li>`).join('')||'<li>See the local story atlas above.</li>'}</ul></div></details>`).join('')}
renderSignals();const themes=[...new Set(STORIES.map(s=>s.theme))].sort();$('#storyTheme').innerHTML+=[...themes].map(t=>`<option>${t}</option>`).join('');renderStories();renderThemes();renderDossiers();
$('#storySearch').addEventListener('input',renderStories);$('#storyTheme').addEventListener('change',renderStories);$('#clearStories').addEventListener('click',()=>{$('#storySearch').value='';$('#storyTheme').value='all';renderStories()});
$$('[data-audience]').forEach(b=>b.addEventListener('click',()=>{document.body.dataset.audience=b.dataset.audience;$$('[data-audience]').forEach(x=>x.classList.toggle('selected',x===b));localStorage.setItem('audience',b.dataset.audience)}));const saved=localStorage.getItem('audience');if(saved)$(`[data-audience="${saved}"]`)?.click();
$('#motion').addEventListener('click',e=>{const v=document.body.classList.toggle('reduce-motion');e.currentTarget.setAttribute('aria-pressed',v);e.currentTarget.textContent=v?'Movement reduced':'Reduce movement'});$('#contrast').addEventListener('click',e=>{const v=document.body.classList.toggle('high-contrast');e.currentTarget.setAttribute('aria-pressed',v)});$('#menu').addEventListener('click',e=>{const open=$('#journey').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});$('#randomStory').addEventListener('click',()=>{$('#stories').scrollIntoView();setTimeout(()=>{const cards=$$('.story');cards[Math.floor(Math.random()*cards.length)]?.focus?.()},500)});
const io=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('in',e.isIntersecting)),{threshold:.12});$$('.signal,.story,.manifesto p,.choice-grid article').forEach(x=>io.observe(x));
